### ISSUE TITLE
Can't find encryption in Key Ring

### ISSUE THREAD

**Issue by JonElster** [lfalck/AzureFunctionsPGPEncrypt#2]
Hi.. I'm running the code but get the following in my Azure function.
**Can't find encryption key in key ring. at PGPcore.Utilities.ReadPublicKey(stream**
Any ideas? Does Azure Key Vault have a KeyRing?  thanks in advance

**Comment by lfalck** [comment]
Hi!

How did you create the public key?

I just tried it now and it works for me using a public key generated with the console app in the repo.
